services:
  # Backend API Service
  - type: web
    name: smart-notes-api
    env: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: GROQ_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: CLIENT_URL
        sync: false  # Set this manually in Render dashboard
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/gif,image/webp
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: smart-notes-frontend
    env: static
    plan: free
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        sync: false  # Set this manually in Render dashboard
      - key: VITE_APP_NAME
        value: Smart Notes Organizer
      - key: VITE_APP_VERSION
        value: 1.0.0
