name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install server dependencies
      run: cd server && npm ci

    - name: Install client dependencies
      run: cd client && npm ci

    - name: Lint server code
      run: cd server && npm run lint --if-present

    - name: Lint client code
      run: cd client && npm run lint

    - name: Run server tests
      run: cd server && npm test --if-present
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/smartnotes-test

    - name: Build client
      run: cd client && npm run build

    - name: Test client build
      run: cd client && npm run preview --if-present

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd server && npm ci
        cd ../client && npm ci

    - name: Run security audit (server)
      run: cd server && npm audit --audit-level moderate

    - name: Run security audit (client)
      run: cd client && npm audit --audit-level moderate

  build:
    needs: [test, security]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        cd server && npm ci
        cd ../client && npm ci

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: client/dist/